name: Actions workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
    - name: Simple Js Action
      uses: actions/hello-javascript-action@v1
      with: 
        who-to-greet: Msawenkosi
    - name: Log Greeting Time
      run: echo "The time is $(date)."